export const ACTIVE_POINTS = [
  { key: 'sun', label: 'Sun', emoji: '☉' },
  { key: 'moon', label: 'Moon', emoji: '☾' },
  { key: 'mercury', label: 'Mercury', emoji: '☿' },
  { key: 'venus', label: 'Venus', emoji: '♀' },
  { key: 'mars', label: 'Mars', emoji: '♂' },
  { key: 'jupiter', label: 'Jupiter', emoji: '♃' },
  { key: 'saturn', label: 'Saturn', emoji: '♄' },
  { key: 'uranus', label: 'Uranus', emoji: '♅' },
  { key: 'neptune', label: 'Neptune', emoji: '♆' },
  { key: 'pluto', label: 'Pluto', emoji: '♇' },
  { key: 'chiron', label: 'Chiron', emoji: '⚷' },
  { key: 'mean_lilith', label: 'Lilith', emoji: '☾‵' },
  { key: 'true_north_lunar_node', label: 'North Node', emoji: '☊' },
  { key: 'true_south_lunar_node', label: 'South Node', emoji: '☋' },
  { key: 'ascendant', label: 'Ascendant', emoji: '↗' },
  { key: 'descendant', label: 'Descendant', emoji: '↘' },
  { key: 'medium_coeli', label: 'MC', emoji: '' },
  { key: 'imum_coeli', label: 'IC', emoji: '' },
];

export const DEFAULT_ACTIVE_KEYS = [
  'sun',
  'moon',
  'mercury',
  'venus',
  'mars',
  'jupiter',
  'saturn',
  'ascendant',
];
